ROAS_DROP_ALERT_THRESHOLD_PCT = 20.0
COST_SPIKE_ALERT_THRESHOLD_PCT = 50.0
ZERO_CONVERSION_DAYS_THRESHOLD = 3
QUALITY_SCORE_LOW_THRESHOLD = 4
IMPRESSION_SHARE_LOST_TO_BUDGET_PCT = 25.0
NEGATIVE_KEYWORD_MIN_SPEND = 5.0
NEGATIVE_KEYWORD_MAX_CONVERSIONS = 0
